version: '2'
services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db:db
  db:
    image: postgres:9.6
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER = "postgres"
      - POSTGRES_PASSWORD = "postgres"
      - POSTGRES_HOST = "db"
      - POSTGRES_PORT = 5432
    ports:
      - "5432:5432"
